# **Auto-Diff for Machine Learning**

## **Notebook overview**
## The following will be covered:
* Explain what Auto-Differentiation (Auto-Diff) is and why it is essential in Machine Learning.
* Describe how PyTorch’s autograd system builds and uses a computational graph.
* Compute gradients automatically using ```.backward()``` and inspect them with ```.grad```.
* Identify and avoid common mistakes when working with autograd (such as breaking thegraph).
* Perform gradient checking to verify whether computed gradients are correct.
* Compare analytical gradients (from autograd) with numerical gradients (finite differences).
* Decide when to use numerical vs analytical gradients in real ML workflows (training vs debugging).

## **Detailed Explanation**
### Introduction — What is Auto-Differentiation?
* In Machine Learning, we try to reduce error/loss just like you try to go downhill. But computing gradients manually for every parameter is:
  * Slow
  * Hard
  * Error-prone
  * Impossible for large models (like nueral networks with thousands of weights)

* So instead of calculating it ourselves, we use:
  > Auto-Diff: A system that automatically computes derivatives for us during training.
* In PyTorch, this is handled by `autograd`. Pytorch is an open source ML library developed by META used mainly for deep learning applications. Machine Learning deals with structured data. Deeplearning is mainly used for ubstructured data.

## **Why Auto-Diff matters**

| **Problem**                                    | **Auto-Diff Solves It By**                         |
|------------------------------------------------|----------------------------------------------------|
| Models have thousands or millions ofparameters | Computes gradients automatically.                  |
| Manual calculus is error-prone                 | Ensures correctness using computational graphs.     |
| We need fast training                          | Optimized low-level gradient operations(uses GPU). |

* Without Auto-Diff → Modern Machine Learning would not be practical.
* Every training loop in ML frameworks (PyTorch, TensorFlow, JAX) depends on it.

## **Key concepts**

### **Concept 1: Tensors**
* Tensors are Multi-dimensional array--Core data structure, support operations like addition, multiplication and matrix multiplication.
* Tensors can be moved to GPU for faster computations.
 > Installing PyTorch: It has different versions according to the hardware specification of the device in use.
    * Standard CPU Installation: `pip install torch torchvision torchaudio`
    * macOS (Apple Silicon M1/M2/M3 or Intel): `pip install torch torchvision`
    * NVIDIA GPU Acceleration (CUDA): `pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126`

In [27]:
# importing PyTorch
import torch

In [28]:
# Example 1: Tensors
x = torch.tensor([1.0, 2.0, 3.0])
print(f'Tensor: {x}, dtype: {type(x)}')

Tensor: tensor([1., 2., 3.]), dtype: <class 'torch.Tensor'>


In [29]:
# Example 2 -Weights
w = torch.tensor([[0.5,1.0],[1.5,2.0],[2.5,3.0]])
w

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000],
        [2.5000, 3.0000]])

In [30]:
# Example 3 - biases
b = torch.tensor([0.1,0.2])
b

tensor([0.1000, 0.2000])

In [31]:
# Example 4
y = torch.matmul(x,w) + b
y

tensor([11.1000, 14.2000])

In [32]:
# Step-by-step process of y

# a = x * w
a = torch.matmul(x,w)
print(f'a = {a}')

# Y = a + b (bias)
Y = a + b
print(f'Y = {Y}')

a = tensor([11., 14.])
Y = tensor([11.1000, 14.2000])


### Explanation of `y = torch.matmul(x,w)+b`
* In W1x + W2y + W0 = 0 (line equation in Machine Learning)
* W1,W2 = 3,4
* In these examples we are kind of using the slope intercept form of line (y = Wx + b)

In [33]:
# Example 5
x2 = torch.tensor([2, 3, 5])
w2 = torch.tensor([1,2,3,4,5,6,7,8,9]).reshape((3,3))
bias = torch.tensor([0.2,0.3,0.4])

y2 = torch.matmul(x2,w2) + bias
print(f'y2 = {y2}')

y2 = tensor([49.2000, 59.3000, 69.4000])


## **Key takeaways**
* Tensor multiplication also gives DYNAMIC COMPUTATION GRAPHS
* Ecosystem: Pytorch has inbuilt modules like torch.nn --> inbuilt support for Neural Networks.
* Pytorch also has torchvision --> for computer visin tasks.
* Flexibility: Pytorch is imperative - code runs as you write it.

### **Concept 2: PyTorch Autograd**
#### What is PyTorch Autograd?
* When we train a machine learning model, especially neural networks, we need to adjust its parameters (weights and biases) to make predictions better over time. The adjustment is done using gradients, which tell us how much each parameter should change to reduce the error(loss).
* However, manually calculating gradients for every model, especially deep neural networks, canbe extremely difficult and time-consuming.

* This is where PyTorch Autograd helps:
  > PyTorch Autograd is an automatic differentiation engine. It
automatically calculates gradients for tensors when we perform operations on them.

#### How Autograd works internally
PyTorch tracks operations performed on tensors in a computational graph.
* Each tensor becomes a node.
* Each operation (like +, ×, ReLU, etc.) becomes an edge between nodes.
* When we call `.backward()`, PyTorch traverses the graph backward to compute gradients.

This process is known as reverse-mode automatic differentiation, which is efficient for machinelearning where we have many parameters but only one final output (loss).

In [34]:
# Example 6

a = torch.tensor(5.0, requires_grad = True)
b = a**3 + 4*a + 2
b.backward() # compute gradient (derivative of b)

print(a.grad)

tensor(79.)


### **Explanation**
The `.backward()` method in PyTorch is used to trigger backpropagation, the process of calculating the gradients of a loss function with respect to all the model's parameters that require gradients. This is a core part of training neural networks, enabling the optimization process.

### **Why PyTorch Autograd matters?**
PyTorch Autograd is the engine behind automatic differentiation, which powers most deeplearning training. Here’s why it’s important:

* Automates Gradient Computation:
  * You no longer need to manually derive complex derivatives for neural networks.
  * This saves time and reduces human errors in gradient calculations.

* Enables efficient training:
  * Autograd computes derivatives on-the-fly using backpropagation.
  * Makes it possible to train large, high-dimensional models without writing cumbersome derivative formulas.

* Supports dynamic computation graphs:
  * PyTorch builds the computation graph dynamically as you execute operations.
  * This flexibility is essential for models with variable inputs or architectures, like RNNs and reinforcement learning.

* Integrates seamlessly with ML workflows:
  * Gradients computed by Autograd directly update model parameters via optimizers.
  * This tight integration reduces boilerplate code and speeds up experimentation.

* Facilitates debugging and visualization:
  * You can inspect `.grad` attributes and track which operations contributed to a gradient.
  * This visibility helps ensure your model is learning as intended.

In short: PyTorch Autograd automates differentiation,
supports dynamic models, and makes training neural networks fast and reliable — without you manually computing any derivatives.



### **Real-world uses of Autograd**

| **Context**                   | **Role of Autograd**                    |
|-------------------------------|-----------------------------------------|
| Training Neural Networks      | Computes gradients for backpropagation  |
| Optimizing Loss Functions     | Determines how parameters should change |
| Fine-tuning Pretrained Models | Updates only selected layers            |
| Reinforcement Learning        | Computes policy gradients               |

### **How it works internally?**

PyTorch builds something called a Computational Graph while performing tensor operations.
* Nodes = tensors
* Edges = operations
* Gradients flow backward through this graph diring `.backward()`

This process is known as Reverse-Mode Automatic Differentiation — good for functions with many inputs and one output (like loss).

In [35]:
# Example 7
x = torch.tensor(3.0, requires_grad = True)
y = x**2 +1 # simple function
y.backward() # compute gradient
print(x.grad)

tensor(6.)


### Explanation of the above code cell
* `requires_grad=True `tells PyTorch to track operations on `x`
* `y.backward()` computes `dy/dx`
* Gradient = `2x + 2` → at `x = 3`, gradient = 8
* That value appears in `x.grad`

### Common confusions:
* Assuming all tensors track gradients by default – Only tensors with `requires_grad=True` are tracked.
* In-place operations – Modifying a tensor in-place can break the computation graph and raise errors.
* Detaching tensors – Forgetting to detach can cause unnecessary memory usage or gradient propagation.

### Key takeaways:
* Autograd automatically computes gradients.
* It builds and uses a computational graph.
* `.backward()` triggers gradient computation.
* `grad` stores the result.
* Essential for backpropagation in neural networks.

### **Concept 3: Gradient checks**
When training machine learning models, especially neural networks, we rely heavily on automatic differentiation (like PyTorch Autograd) to compute gradients. These gradients guide how the model’s parameters get updated during training.

But sometimes, due to:
* Incorrect model implementation
* Wrong loss function formulation
* Custom layer miscalculations

...the gradients computed automatically may be incorrect.
To ensure our gradients are correct, we use Gradient checking.

### **What is gradient checking?**
Gradient Checking is a technique used to verify that the gradients produced by Autograd(analytic gradients) are correct, by comparing them against gradients computed numerically.

* Analytic gradient → Gradient computed by Autograd (fast, precise)
* Numerical gradient → Gradient computed using mathematical approximation (slow but reliable)

Gradient check = compare both
  > * If both gradients are close → implementation is correct
  > * If they differ → something is wrong in your model / loss formula.

### **Why gradient checks matter**
Gradient checks are crucial in machine learning because incorrect gradients can silently break training. Here’s why they matter:

* Detects implementation bugs
  * When you implement custom layers, loss functions, or models, Autograd may give wrong gradients if formulas are incorrect.
  * Gradient checking reveals discrepancies before training goes wrong.

* Ensures reliable learning
  * Neural networks learn by following gradients. Wrong gradients → wrong weight Updates → model fails to converge
  * Checking gradients builds trust that your model is learning correctly.

In [36]:
# Example 8: Simple numerical gradient
import numpy as np
def f(x):
  return x**2 + 3*x

# analytic gradient
def analytic_grad(x):
  return 2*x + 3

# numerical gradient approximation
def numeric_grad(x, eps = (1*0.00001) - 5):
  return (f(x + eps) - f(x - eps)) / (2*eps)

x = 4.0

# comparison
print(f'Analytic: {analytic_grad(x)}')
print(f'Numeric: {numeric_grad(x)}')

Analytic: 11.0
Numeric: 11.0


### Explanation of the above code cell
* `analytic_grad` gives the derivative directly.
* `numeric_grad` approximates the slope by checking how the function changes when wemove slightly left/right from `x`
* If these two match → gradient implementation is correct.

### Key takeaways
* Gradient Check confirms whether your computed gradients are correct.
* It compares analytic gradients vs numerical gradients.
* Essential when building custom layers or loss functions.
* It is used only for debugging, not during actual training (because numerical gradients are slow).

### **Concept 4: Numerical vs Analytical gradients**
#### Analytical gradients
* Analytical gradients are derivatives computed exactly using calculus formulas. In machine learning, these are often computed symbolically (e.g., using PyTorch Autograd).

> Uses of Analytical gradients
  * Provides exact gradients - no approximation errors.
  * Ensures fast convergence in optimization since the gradient points precisely in the steepestdirection.

> Why they matter:
  * Analytical gradients are the backbone of efficient ML training. Without them, gradientdescent becomes impossible for large networks.
  * Exact derivatives ensure your model learns correctly and converges faster.

In [37]:
# Example 9

# Define a simple function
x = torch.tensor(2.0, requires_grad = True)
y = x**3 + 2*x

# Compute gradient automatically
y.backward()
print(x.grad)

tensor(14.)


### Explanation of the above code cell
* Function: f(x) = x³ + 2x
* Analytical derivative: f’(x) = 3x² + 2
* At x=2, gradient = 3*(2²) + 2 = 14
* PyTorch Autograd computed it exactly, no approximation needed.

### Common confusions:
* Thinking Autograd is optional – Beginners sometimes assume you can manually compute gradients easily for all models. In reality, manually computing gradients for large networksis impractical.
* Misunderstanding the gradient shape – Many confuse the output shape of `x.grad` whendealing with multi-dimensional tensors. Each dimension’s gradient corresponds to thatparameter.
* Forgetting `requires_grad=True` – Without it, PyTorch won’t track operations for gradientcomputation.

### Key takeaways
* Analytical gradients are precise and fast.
* They are essential for efficient machine learning training.
* PyTorch Autograd makes computing them seamless.

#### Numerical gradients
Numerical gradients approximate derivatives using small finite differences instead of exactformulas.

> Uses of numerical gradients
  * Provides a way to verify analytical gradients
when implementing models.
  * Can be applied when formulas are too complex or unknown.

> Why they matter:
  * Numerical gradients are crucial for verifying analytical gradients
in custom models or layers.
  * They provide confidence that your gradient computations are correct.

In [43]:
# Example 10

# Function
def f(x):
  return x**3 + 2*x

# Numerical gradient at x = 2
x_val = 2.0
h = 1e-5
numeric_grad = (f(x_val + h) - f(x_val - h)) / (2*h)

print(f'Numeric gradient: {numeric_grad}')

Numeric gradient: 14.000000000180533


### Explanation of the above code cell
* Uses small step h to approximate derivative: `f’(x) ≈ [f(x+h) - f(x-h)] / 2h`
* At `x=2`, numerical gradient ≈ 14, very close to exact analytical value.
* Accuracy depends on step size `h`; too large → error, too small → numerical instability.

### Common confusions:
* Step size selection (h) – Too large → poor approximation; too small → floating-pointerrors. Beginners often pick arbitrary values.
* Difference vs derivative misunderstanding – Some assume numerical gradients give exactresults. They are always approximations.
* Slow computation assumption – Students might not realize numerical gradients areintentionally slow for verification, not training.

### Key takeaways:
* Numerical gradients are approximate but versatile.
* Useful for debugging and gradient verification.
* Slower than analytical gradients, especially for large models.


### Difference between Analytical and Numerical gradients
| **Feature**                   | **Analytical**                     | **Numerical**                                  |
|-------------------------------|------------------------------------|------------------------------------------------|
| Computation                   | Exact using formulas(symbolic)     | Approximate using finite differences           |
| Speed                         | Fast, scalable for large models    | Slower, requires multiple function evaluations |
| Accuracy                      | Precise                            | Slight approximation errors                    |
| Use Case                      | Training models                    | Debugging / verifying gradients                |
| Dependence on ModelComplexity | Works for any differentiable model | Works even if formula is unknown or complex    |

### Summary
* Use analytical gradients for efficient training and production.
* Use numerical gradients to verify or debug your calculations.
* Combining both ensures correctness and reliability in machine learning workflows.

### **Concept 5: Gradient decent**
* Gradient descent is a math optmization algorithm used in ML to find the best parameters.
* It minimizes loss function.
* The gradient descent formula updates a parameter iteratively by moving in the opposite direction of the function's slope.
* Formula for gradient decent:
  > θ(new) = θ(olde) - α ∇ J(θ(new))
* θ: The model parameters (weights)
* α: The learning rate (step size)
* ∇ J(θ): The gradient of the cost function with respect to the parameters

* Accuracy = 1 - loss
* gradient(slope of loss) = dL/dW

In [44]:
# Example 11: Gradient decent in PyTorch

w3 = torch.tensor(10.0, requires_grad = True)
learning_rate = 0.1

for i in range(5):
  loss = (w3 - 3) ** 2

  loss.backward() # To get to the bottom, you need to walk backwards!
  with torch.no_grad(): # Put your pen down. Stop writing in the diary for a second.
    w3 -= learning_rate * w3.grad

  # The above command basically says:
    # Stop recording and just take the step
    # Once the code block finishes, start recording again

  w3.grad.zero_() # This makes the new value of w3 as the default value
  print(f'Step {i+1}: w3 = {w3.item()}, loss = {loss.item()}')

Step 1: w3 = 8.600000381469727, loss = 49.0
Step 2: w3 = 7.4800004959106445, loss = 31.360004425048828
Step 3: w3 = 6.584000587463379, loss = 20.070404052734375
Step 4: w3 = 5.8672003746032715, loss = 12.845060348510742
Step 5: w3 = 5.293760299682617, loss = 8.220837593078613


* Forward pass: asks the algorithm to compute prediction and loss
* Backward pass: computes gradients
* Optimizer step: keeps the updated weight

* If `requires_grad = True`, then PyTorch:
  * remembers the operation
  * remembers which tensors were inputs/outputs
  * attaches a backward function

* During `loss.backward()`, PyTorch:
  * traverses the graph from the output --> input
  * accumulates gradients in each .grad attribute

### Example 12: House price prediction example

* price = `w * area + b`

* House 1: Small (800 size) --> Costs $150

* House 2: Medium (1000 size) --> Costs $180

* House 3: Big (1200 size) --> Costs $220

In [47]:
# Example 12: House price prediction

area = torch.tensor([[800], [1000], [1200]], dtype = torch.float32) # tensor with length, breadth and height
price = torch.tensor([[150], [180], [220]], dtype  = torch.float32) # tensor with prices

w = torch.randn(1, requires_grad = True) # Weight: decides how much "each inch of space" costs.
b = torch.randn(1, requires_grad = True) # Bias: a "starting price" just for walking in the door.

pred = w * area + b
loss = torch.mean((pred - price)**2)
loss.backward()

print(w.grad) # "You need to turn Knob W this much to fix the mistake."
print(b.grad) # "You need to turn Knob B this much to fix the mistake."

tensor([2732912.])
tensor([2661.5112])


### Key Takeaways (Final Recap)
* PyTorch Autograd automatically tracks operations on tensors and computes exact gradients efficiently.
* Gradient Checks verify that analytical gradients are correct using numerical approximations.
* Analytical Gradients are fast and precise, essential for real model training.
* Numerical Gradients are approximate and slow, mainly used for debugging and verification.
* Understanding common pitfalls prevents errors in training, memory usage, and gradientcomputation.
* Together, these concepts ensure that your ML models learn correctly, efficiently, and reliably.